module.exports = [
  {
    name : 'Joe Biden',
    facebookID : Math.round(Math.random()*10000000),
    email : 'joe@gmail.com',
    age : 23,
    sex : 'M',
    employer : 'Government',
    educationInstitution : 'Stanford',
    jobTitle : 'Senator',
    objectID: 'abcdefg'
  },
  {
    name : 'Harry',
    facebookID : Math.round(Math.random()*10000000),
    email : 'will@gmail.com',
    age : 23,
    sex : 'M',
    employer : 'Google',
    educationInstitution : 'Stanford',
    jobTitle : 'Software Engineer',
    objectID: 'abcdefg'
  },
  {
    name : 'Jorge',
    facebookID : Math.round(Math.random()*10000000),
    email : 'g@gmail.com',
    age : 58,
    sex : 'F',
    educationInstitution : 'Stanford',
    employer : 'Facebook' ,
    jobTitle : 'Software Engineer',
    objectID: 'abcdefg'
  },
  {
    name : 'Crooked Willis',
    facebookID : Math.round(Math.random()*10000000),
    email : 'f@facebook.com',
    age : 56,
    sex : 'M',
    employer : 'Facebook',
    educationInstitution : 'Stanford',
    jobTitle : 'Data Analyst',
    objectID: 'abcdefg'
  },
  {
    name : 'Harriet Tubman',
    facebookID : Math.round(Math.random()*10000000),
    email : 'harriet@hotmail.com',
    age : 34,
    sex : 'F',
    employer : 'Yahoo',
    educationInstitution : 'Stanford',
    jobTitle : 'Financial Analyst',
    objectID: 'abcdefg'
  },
  {
    name : 'Cindy',
    facebookID : Math.round(Math.random()*10000000),
    email : 'cindy@gmail.com',
    age : 24,
    sex : 'F',
    employer : 'Facebook',
    educationInstitution : 'Stanford',
    jobTitle : 'CEO',
    objectID: 'abcdefg'
  },
  {
    name : 'Mark Hunderson',
    facebookID : Math.round(Math.random()*10000000),
    email : 'mark@gmail.com',
    age : 43,
    sex : 'M',
    employer : 'Palantir' ,
    educationInstitution : 'Stanford',
    jobTitle : 'CTO',
    objectID: 'abcdefg'
  }
]

var names = [
"Holli Center",
"Robbyn Claypool",
"Tiesha Garica",
"Dorcas Musto",
"Jolynn Martin",
"Alden Esperanza",
"Pearlene Benton",
"Elnora Grumbles",
"Hellen Courser",
"Stanford Herlihy",
"Maurice Claywell",
"Odessa Duffel",
"Constance Wilgus",
"Chelsea Dickinson",
"Wm Mcdowell",
"Vasiliki Snook",
"Waldo Kriss",
"Roselia Koff",
"Oda Mulroy",
"Cheyenne Deland",
"Ardelia Ferrer",
"Earlene Deniz",
"Judie Lessley",
"Lamont Strobel",
"Miki Mcfadden",
"January Wages",
"Valorie Veale",
"Jena Parrett",
"Georgiana Weisbrod",
"Kiesha Mee",
"Boyce Lawry",
"Leatha Murphree",
"Reynaldo Keys",
"Cristi Lynes",
"Consuelo Piano",
"Tania Eoff",
"Franchesca Clausing",
"Kaitlyn Hebert",
"Steve Thibodaux",
"Collin Kimbrell",
"Chris Mcquiggan",
"Ricki Montalbo",
"Clarisa Tibbs",
"Sha Bever",
"Linsey Radtke",
"Ashley Foos",
"Shanon Bryce",
"Antony Raley",
"Soledad Bramhall",
"Caitlyn Bertoli",
"Johnna Moreira",
"Magaly Heenan",
"Florine Leite",
"Shanta Kriss",
"Sal Willhite",
"Sylvie Kanne",
"Kelle Mundt",
"Felicita Parada",
"Janae Granier",
"Freida Sarno",
"Jarrod Triolo",
"Pat Verrett",
"Dino Welty",
"Laurice Browning",
"Herschel Yoon",
"Thea Mero",
"Elisa Ley",
"Annmarie Bramblett",
"Abel Luongo",
"Willa Rondon",
"Tracee Micek",
"Fermina Hy",
"Roseann Jetton",
"Ladawn Garbett",
"Denis Gaver",
"Emilio Baxendale",
"Suzan Arana",
"Blanche Hon",
"Inez Zelaya",
"Valorie Coldiron",
"Denver Jakes",
"Kaitlyn Gregor",
"Susanna Colone",
"Shandi Cashwell",
"Tanya Demery",
"Annamae Hambly",
"Clarita Gloss",
"Edelmira Finley",
"Laurine Bridgewater",
"Melina Sturgis",
"Mariam Mayne",
"Mariano Shull",
"Tyler Magby",
"Genaro Treaster",
"Keila Acker",
"Renda Leo",
"Golda Haugland",
"Kitty Sunderman",
"Shemeka Trojanowski",
"Shu Na",
"Dawna Wattenbarger",
"Mui Weisgerber",
"Yetta Corns",
"Kandis Wendel",
"Karry Acosta",
"Berenice Konen",
"Juliana Klemme",
"Un Caceres",
"Raul Yardley",
"Maren Hart",
"Sena Snider",
"Delpha Markowitz",
"Kimberli Mazzarella",
"Rosio Goodman",
"Shawnta Banker",
"Mason Kesterson",
"Britteny Hatton",
"Sanford Hollen",
"Helene Mikula",
"Monnie Winrow",
"Sofia Paez",
"Kiara Whiteaker",
"Nia Redfearn",
"Illa Berumen",
"Mertie Colonna",
"Latrisha Moret",
"Martina Wachter",
"Valeria Calle",
"Marta Riebe",
"Bob Suh",
"Arnulfo Heisey",
"Addie Silvers",
"Soon Regalado",
"Sirena Sergeant",
"Margene Bethea",
"Jerrod Clem",
"Jazmin Heminger",
"Delora Richman",
"Kyung Kempton",
"Talisha Tichenor",
"Indira Geller",
"Marinda Marks",
"Deann Masek",
"Delisa Mattocks",
"Francesca Stufflebeam",
"Felisha Villatoro",
"Candelaria Bridgers",
"Honey Tarpley",
"Veda Delano",
"Leoma Philippi"
]
