var firstNames = [
  "Holli",
  "Robbyn",
  "Tiesha",
  "Dorcas",
  "Jolynn",
  "Alden",
  "Pearlene",
  "Elnora",
  "Hellen",
  "Stanford",
  "Maurice",
  "Odessa",
  "Constance",
  "Chelsea",
  "Wm",
  "Vasiliki",
  "Waldo",
  "Roselia",
  "Oda",
  "Cheyenne",
  "Ardelia",
  "Earlene",
  "Judie",
  "Lamont",
  "Miki",
  "January",
  "Valorie",
  "Jena",
  "Georgiana",
  "Kiesha",
  "Boyce",
  "Leatha",
  "Reynaldo",
  "Cristi",
  "Consuelo",
  "Tania",
  "Franchesca",
  "Kaitlyn",
  "Steve",
  "Collin",
  "Chris",
  "Ricki",
  "Clarisa",
  "Sha",
  "Linsey",
  "Ashley",
  "Shanon",
  "Antony",
  "Soledad",
  "Caitlyn",
  "Johnna",
  "Magaly",
  "Florine",
  "Shanta",
  "Sal",
  "Sylvie",
  "Kelle",
  "Felicita",
  "Janae",
  "Freida",
  "Jarrod",
  "Pat",
  "Dino",
  "Laurice",
  "Herschel",
  "Thea",
  "Elisa",
  "Annmarie",
  "Abel",
  "Willa",
  "Tracee",
  "Fermina",
  "Roseann",
  "Ladawn",
  "Denis",
  "Emilio",
  "Suzan",
  "Blanche",
  "Inez",
  "Valorie",
  "Denver",
  "Kaitlyn",
  "Susanna",
  "Shandi",
  "Tanya",
  "Annamae",
  "Clarita",
  "Edelmira",
  "Laurine",
  "Melina",
  "Mariam",
  "Mariano",
  "Tyler",
  "Genaro",
  "Keila",
  "Renda",
  "Golda",
  "Kitty",
  "Shemeka",
  "Shu",
  "Dawna",
  "Mui",
  "Yetta",
  "Kandis",
  "Karry",
  "Berenice",
  "Juliana",
  "Un",
  "Raul",
  "Maren",
  "Sena",
  "Delpha",
  "Kimberli",
  "Rosio",
  "Shawnta",
  "Mason",
  "Britteny",
  "Sanford",
  "Helene",
  "Monnie",
  "Sofia",
  "Kiara",
  "Nia",
  "Illa",
  "Mertie",
  "Latrisha",
  "Martina",
  "Valeria",
  "Marta",
  "Bob",
  "Arnulfo",
  "Addie",
  "Soon",
  "Sirena",
  "Margene",
  "Jerrod",
  "Jazmin",
  "Delora",
  "Kyung",
  "Talisha",
  "Indira",
  "Marinda",
  "Deann",
  "Delisa",
  "Francesca",
  "Felisha",
  "Candelaria",
  "Honey",
  "Veda",
  "Leoma"
];

var lastNames = [
  "Center",
  "Claypool",
  "Garica",
  "Musto",
  "Martin",
  "Esperanza",
  "Benton",
  "Grumbles",
  "Courser",
  "Herlihy",
  "Claywell",
  "Duffel",
  "Wilgus",
  "Dickinson",
  "Mcdowell",
  "Snook",
  "Kriss",
  "Koff",
  "Mulroy",
  "Deland",
  "Ferrer",
  "Deniz",
  "Lessley",
  "Strobel",
  "Mcfadden",
  "Wages",
  "Veale",
  "Parrett",
  "Weisbrod",
  "Mee",
  "Lawry",
  "Murphree",
  "Keys",
  "Lynes",
  "Piano",
  "Eoff",
  "Clausing",
  "Hebert",
  "Thibodaux",
  "Kimbrell",
  "Mcquiggan",
  "Montalbo",
  "Tibbs",
  "Bever",
  "Radtke",
  "Foos",
  "Bryce",
  "Raley",
  "Bramhall",
  "Bertoli",
  "Moreira",
  "Heenan",
  "Leite",
  "Kriss",
  "Willhite",
  "Kanne",
  "Mundt",
  "Parada",
  "Granier",
  "Sarno",
  "Triolo",
  "Verrett",
  "Welty",
  "Browning",
  "Yoon",
  "Mero",
  "Ley",
  "Bramblett",
  "Luongo",
  "Rondon",
  "Micek",
  "Hy",
  "Jetton",
  "Garbett",
  "Gaver",
  "Baxendale",
  "Arana",
  "Hon",
  "Zelaya",
  "Coldiron",
  "Jakes",
  "Gregor",
  "Colone",
  "Cashwell",
  "Demery",
  "Hambly",
  "Gloss",
  "Finley",
  "Bridgewater",
  "Sturgis",
  "Mayne",
  "Shull",
  "Magby",
  "Treaster",
  "Acker",
  "Leo",
  "Haugland",
  "Sunderman",
  "Trojanowski",
  "Na",
  "Wattenbarger",
  "Weisgerber",
  "Corns",
  "Wendel",
  "Acosta",
  "Konen",
  "Klemme",
  "Caceres",
  "Yardley",
  "Hart",
  "Snider",
  "Markowitz",
  "Mazzarella",
  "Goodman",
  "Banker",
  "Kesterson",
  "Hatton",
  "Hollen",
  "Mikula",
  "Winrow",
  "Paez",
  "Whiteaker",
  "Redfearn",
  "Berumen",
  "Colonna",
  "Moret",
  "Wachter",
  "Calle",
  "Riebe",
  "Suh",
  "Heisey",
  "Silvers",
  "Regalado",
  "Sergeant",
  "Bethea",
  "Clem",
  "Heminger",
  "Richman",
  "Kempton",
  "Tichenor",
  "Geller",
  "Marks",
  "Masek",
  "Mattocks",
  "Stufflebeam",
  "Villatoro",
  "Bridgers",
  "Tarpley",
  "Delano",
  "Philipp"
];

var jobTitles = [
  "Clothes Model",
  "Speech Pathologist",
  "Ship Painter Helper",
  "Crew Chief",
  "Social Science Manager",
  "Cardiac Surgeon",
  "Ice Skating Coach",
  "Horologist",
  "Licensed Massage Practitioner",
  "Loan Counselor",
  "Sewage Plant Operator",
  "Remote Broadcast Engineer",
  "Outboard System Operator",
  "Prosthetics Lab Technician",
  "Paintings Conservator",
  "Catalog Librarian",
  "Swimming Pool Plasterer Helper",
  "Technical Surveillance Countermeasures (Tscm) Specialist",
  "Fire Claims Adjuster",
  "Medical Illustrator",
  "Flight Engineer Manager",
  "Cost Analyst",
  "Equal Employment Opportunity Representative",
  "Electrician's Assistant",
  "Field Artillery Officer",
  "Software Engineer",
  "Product Manager",
  "Software Engineer in Test",
  "Consultant",
  "Director of Operations",
  "CEO",
  "CTO",
  "CMO"
];

var educationInstitution = [
  "Stanford",
  "University of Toronto",
  "MIT",
  "",
  "UCI",
  "Rutgers"
];

var employers = [
  "Apple",
  "Google",
  "Microsoft",
  "Amazon",
  "Facebook",
  "Dropbox",
  "Box",
  "Groupon",
  "Space X",
  "Solar City"
]

var randomElement = function(array){
  var randomIndex = Math.floor(Math.random() * array.length);
  return array[randomIndex];
}

var generateObjectID = function () {
  var size = 8;
  var letters = ["a","b","c","d","e","f","g","h","i",
    "j","k","l","m","n","o","p",
    "q","r","s","t","u","v","w",
    "x","y","z"];
  var objID = '';
  for (var i = 0; i < size; i ++) {
    objID += randomElement(letters);
  }
  return objID;
}

var generateRandomUser = function () {
  var user = {};
  user.name = randomElement(firstNames) + ' ' + randomElement(lastNames);
  user.facebookID = Math.round(Math.random() * 10000000);
  user.email = user.name.replace(' ', '_') + '@gmail.com';
  user.age = Math.round(Math.random() * 100);
  user.sex = Math.round(Math.random()) === 1 ? 'F' : 'M';
  user.employer = randomElement(employers);
  user.educationInstitution = randomElement(educationInstitution);
  user.jobTitle = randomElement(jobTitles);
  user.objectID = generateObjectID();
  return user;
}

module.exports = generateRandomUser;
