module.exports = [
  "Indian food for lunch",
  "Watch Star Wars",
  "Mexican Food",
  "Eat lunch with cool tech peepz",
  "Take a break dancing class",
  "Jam on guitar",
  "Go climbing at Mission Cliffs",
  "Go for a coffee",
  "Talk about life",
  "Eat chicken",
  "Buy a wool coat with me",
  "Go watch the Warriors tonight",
  "Chill",
  "Lunch at Show Dogs",
  "Basketball",
  "Go to the beach, see a cashier, see if there are any little buggers there",
  "Eat",
  "Check me out in a suit",
  "See if I can handle these roses",
  "Buy spam without the salty",
  "Bleh",
  "Buy some goat cheese and asparagus",
  "Head to Rainbow to get some things",
  "Read some Socrates",
  "Read The Giver",
  "Chuck a ball around",
  "Eat dinner",
  "Eat a snack",
  "Select a ripe apricot",
  "Head to the ball with me",
  "Buy me an umbrella",
  "Tickets to see City & Colour",
  "Play chamber music with me",
  "Let's go boulder"
];
