# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Wandoo' do
    pod 'Parse', '~> 1.10'
    pod 'FBSDKCoreKit', '~> 4.9.0-beta2'
    pod 'FBSDKLoginKit', '~> 4.9.0-beta2'
    pod 'FBSDKShareKit'
    pod 'ParseFacebookUtilsV4', '~> 1.9'
    pod 'Atlas'
    pod 'ParseUI'
    pod 'SVProgressHUD'

    workspace 'wandoo'
end

post_install do |installer|
    plist_buddy = "/usr/libexec/PlistBuddy"
    installer.pods_project.targets.each do |target|
        plist = "Pods/Target Support Files/#{target}/Info.plist"
        original_version = `#{plist_buddy} -c "Print CFBundleShortVersionString" "#{plist}"`.strip
        changed_version = original_version[/(\d+\.){1,2}(\d+)?/]
        unless original_version == changed_version
            puts "Fix version of Pod #{target}: #{original_version} => #{changed_version}"
            `#{plist_buddy} -c "Set CFBundleShortVersionString #{changed_version}" "Pods/Target Support Files/#{target}/Info.plist"`
        end
    end
end

