# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Wandoo' do
    pod 'Parse', '~> 1.10'
    pod 'FBSDKCoreKit', '~> 4.9.0-beta2'
    pod 'FBSDKLoginKit', '~> 4.9.0-beta2'
    pod 'FBSDKShareKit'
    pod 'ParseFacebookUtilsV4', '~> 1.9'
    pod 'Atlas'
    pod 'ParseUI'
    pod 'SVProgressHUD'

    workspace 'wandoo'
end

